services:
  invenchecker:
    build: .
    expose:
      - "33001"
    networks:
      - invenchecker
    restart: unless-stopped
    volumes:
      - /opt/data/invenchecker:/app/data
networks:
  invenchecker:
    external: true
